-- MySQL Script generated by MySQL Workbench
-- Sat Dec 30 00:19:44 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gestorturnosdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestorturnosdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestorturnosdb` DEFAULT CHARACTER SET utf8 ;
USE `gestorturnosdb` ;

-- -----------------------------------------------------
-- Table `gestorturnosdb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`Admin` (
  `idAdmin` INT(11) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `NomeUtilizador` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`Aluno` (
  `NrAluno` INT(11) NOT NULL,
  `Estatuto` TINYINT(1) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `NomeUtilizador` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NrAluno`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`Docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`Docente` (
  `NrDocente` INT(11) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `NomeUtilizador` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NrDocente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`Sala` (
  `idSala` INT(11) NOT NULL,
  `Identificacao` VARCHAR(45) NOT NULL,
  `Capacidade` INT(11) NOT NULL,
  PRIMARY KEY (`idSala`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`UC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`UC` (
  `Abreviatura` VARCHAR(10) NOT NULL,
  `Designacao` VARCHAR(45) NOT NULL,
  `Semestre` INT(11) NOT NULL,
  `NrDocenteResponsavel` INT(11) NOT NULL,
  PRIMARY KEY (`Abreviatura`),
  INDEX `fk_UC_Docente1_idx` (`NrDocenteResponsavel` ASC),
  CONSTRAINT `fk_UC_Docente1`
    FOREIGN KEY (`NrDocenteResponsavel`)
    REFERENCES `gestorturnosdb`.`Docente` (`NrDocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`Turno` (
  `idTurno` INT(11) NOT NULL,
  `UCAbreviatura` VARCHAR(10) NOT NULL,
  `Docente_idDocente` INT(11) NOT NULL,
  `Sala_idSala` INT(11) NOT NULL,
  `Numero` INT(11) NOT NULL,
  `Inicio` TIME NOT NULL,
  `Fim` TIME NOT NULL,
  `DiaDaSemana` INT(11) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTurno`),
  INDEX `fk_Turno_UC1_idx` (`UCAbreviatura` ASC),
  INDEX `fk_Turno_Docente1_idx` (`Docente_idDocente` ASC),
  INDEX `fk_Turno_Sala1_idx` (`Sala_idSala` ASC),
  CONSTRAINT `fk_Turno_Docente1`
    FOREIGN KEY (`Docente_idDocente`)
    REFERENCES `gestorturnosdb`.`Docente` (`NrDocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_Sala1`
    FOREIGN KEY (`Sala_idSala`)
    REFERENCES `gestorturnosdb`.`Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_UC1`
    FOREIGN KEY (`UCAbreviatura`)
    REFERENCES `gestorturnosdb`.`UC` (`Abreviatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`RegistoPresenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`RegistoPresenca` (
  `idRegistoPresenca` INT(11) NOT NULL,
  `NrAula` INT(11) NOT NULL,
  `Turno_idTurno` INT(11) NOT NULL,
  PRIMARY KEY (`idRegistoPresenca`),
  INDEX `fk_RegistoPresenca_Turno1_idx` (`Turno_idTurno` ASC),
  CONSTRAINT `fk_RegistoPresenca_Turno1`
    FOREIGN KEY (`Turno_idTurno`)
    REFERENCES `gestorturnosdb`.`Turno` (`idTurno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`Aluno_RegistoPresenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`Aluno_RegistoPresenca` (
  `RegistoPresenca_idRegistoPresenca` INT(11) NOT NULL,
  `Aluno_NrAluno` INT(11) NOT NULL,
  `Presente` TINYINT(1) NOT NULL,
  INDEX `fk_Aluno_RegistoPresenca_RegistoPresenca1_idx` (`RegistoPresenca_idRegistoPresenca` ASC),
  INDEX `fk_Aluno_RegistoPresenca_Aluno1_idx` (`Aluno_NrAluno` ASC),
  CONSTRAINT `fk_Aluno_RegistoPresenca_Aluno1`
    FOREIGN KEY (`Aluno_NrAluno`)
    REFERENCES `gestorturnosdb`.`Aluno` (`NrAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_RegistoPresenca_RegistoPresenca1`
    FOREIGN KEY (`RegistoPresenca_idRegistoPresenca`)
    REFERENCES `gestorturnosdb`.`RegistoPresenca` (`idRegistoPresenca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`Aluno_Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`Aluno_Turno` (
  `Turno_idTurno` INT(11) NOT NULL,
  `Aluno_NrAluno` INT(11) NOT NULL,
  INDEX `fk_Aluno_Turno_Turno1_idx` (`Turno_idTurno` ASC),
  INDEX `fk_Aluno_Turno_Aluno1_idx` (`Aluno_NrAluno` ASC),
  CONSTRAINT `fk_Aluno_Turno_Aluno1`
    FOREIGN KEY (`Aluno_NrAluno`)
    REFERENCES `gestorturnosdb`.`Aluno` (`NrAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Turno_Turno1`
    FOREIGN KEY (`Turno_idTurno`)
    REFERENCES `gestorturnosdb`.`Turno` (`idTurno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`NotificacaoPresenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`NotificacaoPresenca` (
  `idNotificacao` INT(11) NOT NULL AUTO_INCREMENT,
  `Aluno_NrAluno` INT(11) NOT NULL,
  `Docente_IdDocente` INT(11) NOT NULL,
  `Turno_idTurno` INT(11) NOT NULL,
  PRIMARY KEY (`idNotificacao`),
  INDEX `fk_NotificacaoPresenca_Aluno1_idx` (`Aluno_NrAluno` ASC),
  INDEX `fk_NotificacaoPresenca_Docente1_idx` (`Docente_IdDocente` ASC),
  INDEX `fk_NotificacaoPresenca_Turno1_idx` (`Turno_idTurno` ASC),
  CONSTRAINT `fk_NotificacaoPresenca_Aluno1`
    FOREIGN KEY (`Aluno_NrAluno`)
    REFERENCES `gestorturnosdb`.`Aluno` (`NrAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NotificacaoPresenca_Docente1`
    FOREIGN KEY (`Docente_IdDocente`)
    REFERENCES `gestorturnosdb`.`Docente` (`NrDocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NotificacaoPresenca_Turno1`
    FOREIGN KEY (`Turno_idTurno`)
    REFERENCES `gestorturnosdb`.`Turno` (`idTurno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`PropostaTroca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`PropostaTroca` (
  `idPropostaTroca` INT(11) NOT NULL,
  `Proponente_NrAluno` INT(11) NOT NULL,
  `Proponente_idTurno` INT(11) NOT NULL,
  `Oblato_NrAluno` INT(11) NULL DEFAULT NULL,
  `Oblato_idTurno1` INT(11) NOT NULL,
  `Docente_idDocente` INT(11) NULL DEFAULT NULL,
  `Estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPropostaTroca`),
  INDEX `fk_Propostas de Troca_Aluno1_idx` (`Proponente_NrAluno` ASC),
  INDEX `fk_Propostas de Troca_Aluno2_idx` (`Oblato_NrAluno` ASC),
  INDEX `fk_Propostas de Troca_Turno1_idx` (`Proponente_idTurno` ASC),
  INDEX `fk_Propostas de Troca_Turno2_idx` (`Oblato_idTurno1` ASC),
  INDEX `fk_Propostas de Troca_Docente1_idx` (`Docente_idDocente` ASC),
  CONSTRAINT `fk_Propostas de Troca_Aluno1`
    FOREIGN KEY (`Proponente_NrAluno`)
    REFERENCES `gestorturnosdb`.`Aluno` (`NrAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Propostas de Troca_Aluno2`
    FOREIGN KEY (`Oblato_NrAluno`)
    REFERENCES `gestorturnosdb`.`Aluno` (`NrAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Propostas de Troca_Docente1`
    FOREIGN KEY (`Docente_idDocente`)
    REFERENCES `gestorturnosdb`.`Docente` (`NrDocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Propostas de Troca_Turno1`
    FOREIGN KEY (`Proponente_idTurno`)
    REFERENCES `gestorturnosdb`.`Turno` (`idTurno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Propostas de Troca_Turno2`
    FOREIGN KEY (`Oblato_idTurno1`)
    REFERENCES `gestorturnosdb`.`Turno` (`idTurno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
