-- MySQL Script generated by MySQL Workbench
-- Sat Dec 30 21:24:18 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gestorturnosdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestorturnosdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestorturnosdb` DEFAULT CHARACTER SET utf8 ;
USE `gestorturnosdb` ;

-- -----------------------------------------------------
-- Table `gestorturnosdb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`Admin` (
  `NomeUtilizador` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NomeUtilizador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`Aluno` (
  `NomeUtilizador` VARCHAR(45) NOT NULL,
  `Estatuto` TINYINT(1) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NomeUtilizador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`Docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`Docente` (
  `NomeUtilizador` VARCHAR(45) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`NomeUtilizador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`UC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`UC` (
  `Abreviatura` VARCHAR(10) NOT NULL,
  `Designacao` VARCHAR(45) NOT NULL,
  `Semestre` INT(11) NOT NULL,
  `Docente_NomeUtilizador` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Abreviatura`),
  INDEX `fk_UC_Docente1_idx` (`Docente_NomeUtilizador` ASC),
  CONSTRAINT `fk_UC_Docente1`
    FOREIGN KEY (`Docente_NomeUtilizador`)
    REFERENCES `gestorturnosdb`.`Docente` (`NomeUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`Sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`Sala` (
  `Identificacao` VARCHAR(45) NOT NULL,
  `Capacidade` INT(11) NOT NULL,
  PRIMARY KEY (`Identificacao`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`Turno` (
  `idTurno` INT(11) NOT NULL AUTO_INCREMENT,
  `UCAbreviatura` VARCHAR(10) NOT NULL,
  `Docente_NomeUtilizador` VARCHAR(45) NOT NULL,
  `Sala_Identificacao` VARCHAR(45) NOT NULL,
  `Numero` INT(11) NOT NULL,
  `Inicio` TIME NOT NULL,
  `Fim` TIME NOT NULL,
  `DiaDaSemana` INT(11) NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTurno`),
  INDEX `fk_Turno_UC1_idx` (`UCAbreviatura` ASC),
  INDEX `fk_Turno_Docente1_idx` (`Docente_NomeUtilizador` ASC),
  INDEX `fk_Turno_Sala1_idx` (`Sala_Identificacao` ASC),
  CONSTRAINT `fk_Turno_UC1`
    FOREIGN KEY (`UCAbreviatura`)
    REFERENCES `gestorturnosdb`.`UC` (`Abreviatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_Docente1`
    FOREIGN KEY (`Docente_NomeUtilizador`)
    REFERENCES `gestorturnosdb`.`Docente` (`NomeUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Turno_Sala1`
    FOREIGN KEY (`Sala_Identificacao`)
    REFERENCES `gestorturnosdb`.`Sala` (`Identificacao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`RegistoPresenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`RegistoPresenca` (
  `idRegistoPresenca` INT(11) NOT NULL AUTO_INCREMENT,
  `NrAula` INT(11) NOT NULL,
  `Turno_idTurno` INT(11) NOT NULL,
  PRIMARY KEY (`idRegistoPresenca`),
  INDEX `fk_RegistoPresenca_Turno1_idx` (`Turno_idTurno` ASC),
  CONSTRAINT `fk_RegistoPresenca_Turno1`
    FOREIGN KEY (`Turno_idTurno`)
    REFERENCES `gestorturnosdb`.`Turno` (`idTurno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`Aluno_RegistoPresenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`Aluno_RegistoPresenca` (
  `RegistoPresenca_idRegistoPresenca` INT(11) NOT NULL,
  `Aluno_NomeUtilizador` VARCHAR(45) NOT NULL,
  `Presente` TINYINT(1) NOT NULL,
  INDEX `fk_Aluno_RegistoPresenca_RegistoPresenca1_idx` (`RegistoPresenca_idRegistoPresenca` ASC),
  INDEX `fk_Aluno_RegistoPresenca_Aluno1_idx` (`Aluno_NomeUtilizador` ASC),
  PRIMARY KEY (`RegistoPresenca_idRegistoPresenca`, `Aluno_NomeUtilizador`),
  CONSTRAINT `fk_Aluno_RegistoPresenca_RegistoPresenca1`
    FOREIGN KEY (`RegistoPresenca_idRegistoPresenca`)
    REFERENCES `gestorturnosdb`.`RegistoPresenca` (`idRegistoPresenca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_RegistoPresenca_Aluno1`
    FOREIGN KEY (`Aluno_NomeUtilizador`)
    REFERENCES `gestorturnosdb`.`Aluno` (`NomeUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`Aluno_Turno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`Aluno_Turno` (
  `Turno_idTurno` INT(11) NOT NULL,
  `Aluno_NomeUtilizador` VARCHAR(45) NOT NULL,
  INDEX `fk_Aluno_Turno_Turno1_idx` (`Turno_idTurno` ASC),
  INDEX `fk_Aluno_Turno_Aluno1_idx` (`Aluno_NomeUtilizador` ASC),
  PRIMARY KEY (`Turno_idTurno`, `Aluno_NomeUtilizador`),
  CONSTRAINT `fk_Aluno_Turno_Turno1`
    FOREIGN KEY (`Turno_idTurno`)
    REFERENCES `gestorturnosdb`.`Turno` (`idTurno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_Turno_Aluno1`
    FOREIGN KEY (`Aluno_NomeUtilizador`)
    REFERENCES `gestorturnosdb`.`Aluno` (`NomeUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`NotificacaoPresenca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`NotificacaoPresenca` (
  `idNotificacao` INT(11) NOT NULL AUTO_INCREMENT,
  `Aluno_NomeUtilizador` VARCHAR(45) NOT NULL,
  `Turno_idTurno` INT(11) NOT NULL,
  `Docente_NomeUtilizador` VARCHAR(45) NOT NULL,
  `NrAula` INT NOT NULL,
  PRIMARY KEY (`idNotificacao`),
  INDEX `fk_NotificacaoPresenca_Turno1_idx` (`Turno_idTurno` ASC),
  INDEX `fk_NotificacaoPresenca_Aluno1_idx` (`Aluno_NomeUtilizador` ASC),
  INDEX `fk_NotificacaoPresenca_Docente1_idx` (`Docente_NomeUtilizador` ASC),
  CONSTRAINT `fk_NotificacaoPresenca_Turno1`
    FOREIGN KEY (`Turno_idTurno`)
    REFERENCES `gestorturnosdb`.`Turno` (`idTurno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NotificacaoPresenca_Aluno1`
    FOREIGN KEY (`Aluno_NomeUtilizador`)
    REFERENCES `gestorturnosdb`.`Aluno` (`NomeUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NotificacaoPresenca_Docente1`
    FOREIGN KEY (`Docente_NomeUtilizador`)
    REFERENCES `gestorturnosdb`.`Docente` (`NomeUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `gestorturnosdb`.`PropostaTroca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestorturnosdb`.`PropostaTroca` (
  `idPropostaTroca` INT(11) NOT NULL,
  `Proponente_NomeUtilizador` VARCHAR(45) NOT NULL,
  `Proponente_idTurno` INT(11) NOT NULL,
  `Oblato_NomeUtilizador` VARCHAR(45) NULL,
  `Oblato_idTurno` INT(11) NOT NULL,
  `Docente_NomeUtilizador` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPropostaTroca`),
  INDEX `fk_Propostas de Troca_Turno1_idx` (`Proponente_idTurno` ASC),
  INDEX `fk_Propostas de Troca_Turno2_idx` (`Oblato_idTurno` ASC),
  INDEX `fk_PropostaTroca_Docente1_idx` (`Docente_NomeUtilizador` ASC),
  INDEX `fk_PropostaTroca_Aluno1_idx` (`Proponente_NomeUtilizador` ASC),
  INDEX `fk_PropostaTroca_Aluno2_idx` (`Oblato_NomeUtilizador` ASC),
  CONSTRAINT `fk_Propostas de Troca_Turno1`
    FOREIGN KEY (`Proponente_idTurno`)
    REFERENCES `gestorturnosdb`.`Turno` (`idTurno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Propostas de Troca_Turno2`
    FOREIGN KEY (`Oblato_idTurno`)
    REFERENCES `gestorturnosdb`.`Turno` (`idTurno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PropostaTroca_Docente1`
    FOREIGN KEY (`Docente_NomeUtilizador`)
    REFERENCES `gestorturnosdb`.`Docente` (`NomeUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PropostaTroca_Aluno1`
    FOREIGN KEY (`Proponente_NomeUtilizador`)
    REFERENCES `gestorturnosdb`.`Aluno` (`NomeUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PropostaTroca_Aluno2`
    FOREIGN KEY (`Oblato_NomeUtilizador`)
    REFERENCES `gestorturnosdb`.`Aluno` (`NomeUtilizador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
